### PR TITLE
fix missing active_run() error in gbt-regression

### PR DESCRIPTION
**Pull request by jimthompson5802**
Running gbt-regression sample app received this error:
```
Test RMSE: 660.6568383770832
Training set score: 0.9741249511269733
Test set score: 0.9728833667498216
Traceback (most recent call last):
  File "main_gbt.py", line 51, in <module>
    args.training_data_path, args.test_data_path)
  File "/Users/jim/Desktop/databricks_mlflow/mlflow-apps/apps/gbt-regression/train_gbt.py", line 66, in train
    run_id = mlflow.tracking.active_run().info.run_uuid
AttributeError: module 'mlflow.tracking' has no attribute 'active_run'
=== Run (ID '8bbfc9b89a374c6682792fe12b860aa4') failed ===
```

From what I can tell `mlflow.tracking` was refactored and location of `active_run()` was moved.  This pull request revises the code to reflect the new location of `active_run()`.

Here is a run after the fix:
```
(mlflow) Jim-MacBook-Pro:bin jim$ mlflow run $mlflowapps/apps/gbt-regression -P train="$temp/train_diamonds.parquet" -P test="$temp/test_diamonds.parquet" -P label-col="price"
=== Created directory /var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/tmp2s0twl2y for downloading remote URIs passed to arguments of type 'path' ===
=== Running command 'source activate mlflow-6876bc479f0d8935eada0e0b89f32993b9abf06a && python main_gbt.py /var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/tmp.o5LmpvAX/train_diamonds.parquet /var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/tmp.o5LmpvAX/test_diamonds.parquet 100 3 0.1 rmse price' in run with ID 'b8708a0dbf194f42a178f448cf1ee718' === 
train:                 /var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/tmp.o5LmpvAX/train_diamonds.parquet
test:                  /var/folders/8_/h2tjc94d2y5fwx8dhbcrnbfc0000gn/T/tmp.o5LmpvAX/test_diamonds.parquet
n_trees:               100
m-depth:               3
learning-rate:         0.1
loss:                  rmse
label-col:             price
feat-cols:             carat
feat-cols:             cut
feat-cols:             color
feat-cols:             clarity
feat-cols:             depth
feat-cols:             table
feat-cols:             x
feat-cols:             y
feat-cols:             z
Test RMSE: 660.6568383770832
Training set score: 0.9741249511269733
Test set score: 0.9728833667498216
Run with id b8708a0dbf194f42a178f448cf1ee718 finished
=== Run (ID 'b8708a0dbf194f42a178f448cf1ee718') succeeded ===
```

@juntai-zheng   @smurching   if this seems like a reasonable fix, I can retrofit the fix in the other samples.

### CODE REVIEW

**Comment by smurching** [comment]
@jimthompson5802 thanks so much for the catch & PR! Your thought of porting over the `active_run` fix to the other apps does indeed make sense. It turns out there were actually a number of APIs in MLflow that have changed, so I just pushed a commit to address those changes - let me know if the changes make sense, and then hopefully we can go ahead & merge this :)

**Comment by jimthompson5802** [comment]
@smurching Thank you for the feedback.  Since I'm just learning mlflow and this is the first time I'm contributing to an open source project, I could use a little guidance.  

From what I can tell you fixed some/all of the issues with the build test with the "Fix TF test" commit.  I was in the process of trying to fix the build test issues.  This PR started with the gbt-regression app but now seems to be expanding beyond that.  This brings up couple of questions:

* Does the focus of this PR to account for all the api updates to all the examples or should a separate PR for each example apps: dnn, gbt, linear be created?
* Do I focus on changes in the `apps` directory only or should I work on both changes needed in `apps` and `tests`?

**Comment by jimthompson5802** [comment]
@smurching I took a closer look at the changes.  They look reasonable to me.  I'm OK with merging the PR.   I'll create separate PR for other changes to the other models in the `apps` directory.

**Comment by smurching** [comment]
@jimthompson5802 ah great questions - yeah my updates were actually aimed at fixing up the tests to get your fix in, but in the process of doing so I ended up fixing the other apps as well (i.e. after this PR is merged, all the apps should work, as verified by the integration tests under the `tests` directory). Sorry I should have checked in with you before pushing the test fixes, didn't realize you'd been looking into that!

> Does the focus of this PR to account for all the api updates to all the examples or should a separate PR for each example apps: dnn, gbt, linear be created?

In this case changes to all the apps are necessary, since tests only pass once all the breaking MLflow API changes are accounted for across the apps.

However, IMO it's definitely best in general for PRs to broken down into smaller PRs when possible, within reason (i.e. I'd say ~300 lines is a good upper bound for PR length). When there are clear ways to break up unrelated functionality (i.e. changes to different apps) it's also helpful to split those into separate PRs too. The main advantage is that it's easier to review & be confident in the correctness of incremental small changes rather than having to merge one big patch. 

> Do I focus on changes in the apps directory only or should I work on both changes needed in apps and tests?

Good question, for both mlflow-apps & mlflow we have Travis CI configured to run against all PRs so that we can verify tests pass before merging in new code. In this case changes to both apps and tests were necessary to get the tests to pass.

Thanks again for catching this issue & making the PR. If there are other things you'd like to contribute to MLflow or mlflow-apps, we'd be happy to review them :)! A great place to start is by looking at open Github issues, and if there are larger features you'd like to contribute it's helpful to create an associated Github issue first so that the feature can be discussed.

**Comment by smurching** [comment]
Will go ahead and merge this, thanks @jimthompson5802!

**Pull request merged**
